server:
  port: 8801

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/z_exercise?useSSL=false&useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
    username: root
    password: ebiz.1276