server:
  port: 8080
spring:
  activemq:
    broker-url: tcp://127.0.0.1:61616
    user: one
    password: one
    pool:
      enabled: true
    packages:
      trust-all: true #使用ObjectMessage传输对象必备包，没有这个会报ClassNotFound找不到类异常
  jms:
    pub-sub-domain: true #默认只有P2P模式，加这个启用P/S模式，可以发主题消息
